### ISSUE TITLE
compare to serializerr

### ISSUE THREAD

**Issue by timoxley** [sindresorhus/serialize-error#1]
What is the difference here, if any?

https://www.npmjs.com/package/serializerr

**Comment by timoxley** [comment]
Ahh, seems `serializerr` will grab proto properties as well… I cannot recall exactly why I did this but IIRC it's not uncommon for libs/apps to extend Errors via `Object.create(err)` and subsequently all of the `.code` and `.stack` etc get lost if you don't traverse the chain.

**Comment by sindresorhus** [comment]
Seems I missed this one. From what I can tell today, the main differences is that this one also handles circular references and it handles the error being a non-object.
