### ISSUE TITLE
Does not handle circular references.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/serialize-error#2]
If an error contains a circular reference (entirely possible with AssertionErrors `actual`, and `expected`), serialization will fail.

Reference: https://github.com/sindresorhus/ava/pull/187

**Comment by sindresorhus** [comment]
Hah, I never thought of the use-case of the error having added properties with circular references. Should be easy to fix though.

**Comment by jamestalmage** [comment]
Yep. But something you do in this lib makes the difference for the Windows and Node 0.10 combination (all other test variants pass). (speaking of the ava issue above)

I am guessing one of the properties you delete does something.

So very frustrating.

**Comment by sindresorhus** [comment]
Isn't this just flaky tests as commented on in https://github.com/sindresorhus/ava/pull/187? Or is it something else?

**Comment by jamestalmage** [comment]
No. Those only seem flaky on AppVeyor (everything has consistently passed/failed in my Parallels VM).

On Node 0.10 Win32, using Object.getOwnPropertyNames instead of Object.keys seemed to make a difference. 

I don't get why it only made a difference for that specific combo of OS/engine. I could just be [seeing things](https://en.m.wikipedia.org/wiki/Apophenia)

**Comment by jamestalmage** [comment]
https://github.com/jonpacker/destroy-circular/pull/1

Has sat for over a week with no action. If it does not resolve soon, we should just reimplement here.

**Comment by sindresorhus** [comment]
@jamestalmage I don't see the point of waiting any longer. It should be easy to implement it here inline. It's just pushing everything to a `seen` array and then checking it.
