### ISSUE TITLE
Consider Object.toJSON() method

### ISSUE THREAD

**Issue by samchon** [sindresorhus/serialize-error#20]
Some program defines custom error type (e.g. `MyError`) and the custom error type also may have the `toJSON()` method, that would be used in `JSON.stringify()`. In such reason, I recommend `serializeError` function to inspects the `toJSON()` method first.

```typescript
class MyError extends Error
{
    public readonly code: number;
    public readonly type: string;
    
    public constructor(code: number, type: string, message: string);
    public toJSON(): object
    {
        return {
            name: this.name, stack: this.stack, message: this.message,
            code: this.code, type: this.type
        };
    }
}
```

**Comment by sindresorhus** [comment]
Makes sense. PR welcome.

**Comment by samchon** [comment]
PR https://github.com/sindresorhus/serialize-error/pull/21

**Comment by moltar** [comment]
On the other hand, I am using `serializeError` to implement `toJSON` method:

```
  public toJSON() {
    return serializeError(this)
  }
```

So this would be a breaking change.

**Comment by sindresorhus** [comment]
We could use a `Symbol` to prevent self-recursive serialization.
