### ISSUE TITLE
change in v5: `const {inspect} = require('util');` can lead to web bundle bloat

### ISSUE THREAD

**Issue by dylang** [sindresorhus/serialize-error#26]
This was added in v5 for `deserializeError`:

```ts
const {inspect} = require('util');
```

This adds about 8KB to web bundles, which can be significant, especially in projects not using `deserializeError`.

Possible solutions:

* Not worry about 8KB and tell developers to use v4 if bundle size is of concern.
* Separate `serializeError` into a separate file that can be imported without the `deserializeError` code.
* Separate `deserializeError` into a new module.
* Publish code with ES6-style `import`, add `sideEffects: false` to the `package.json` to enable tree shaking in the module.
* Other ideas?

**Comment by sindresorhus** [comment]
I didn't realize people used this in the browser.

We could maybe add `{"browser": {"util": false}` to package.json and check for its existence before using it? However, then the output will not be consistent between Node.js and the browser. Not sure that matters. Or we could find a simpler way to show the type. It's not important. It's just a bonus to make it easier to debug passed values that are not really deserializable as errors.

We should probably also guard https://github.com/sindresorhus/serialize-error/blob/480ed369823b089ac8c75092d59c1d1f7390350e/index.js#L8 then, as it doesn't exist in Firefox.

**Comment by rohan-deshpande** [comment]
Thanks for this issue. I think this is a really handy lib and making it universal is a good idea! I support this approach:

> Or we could find a simpler way to show the type. It's not important. It's just a bonus to make it easier to debug passed values that are not really deserializable as errors.

Basically the only reason for using `inspect` here is to be able to find out what happened right? Just for debugging purposes? I think if there is some light weight way to implement this that'd be ideal, maybe just use `JSON.stringify` if it's an object?

**Comment by sindresorhus** [comment]
Yeah, we could probably just use JSON.stringify.

**Comment by vladimiry** [comment]
> I didn't realize people used this in the browser.

Using `deserializeError` in browser is a quite common case. Like when you serialize the error on backed and the serve it to in-browser client or `main process` => `renderer process` interaction in the case of @electron IPC use.

[Such change](https://github.com/vladimiry-playground/serialize-error/commit/a2c28c7f7f4ce409780ac7c6918d8ea875934a43) seems to be working well.

**Comment by sindresorhus** [comment]
@vladimiry A PR would be welcome :)

**Comment by vladimiry** [comment]
Going to adjust tests and PR then.

**Comment by vladimiry** [comment]
PR placed: #27.
