### ISSUE TITLE
Consider making common error properties non enumerable

### ISSUE THREAD

**Issue by Weakky** [sindresorhus/serialize-error#29]
## Description

Native JS errors don't have its properties enumerable. What this means is that the `name`, `stack` and `message` properties do not appear when console.logging errors.

Notice the `name` and `message` property appearing below.

![image](https://user-images.githubusercontent.com/25233379/81183679-bf509700-8faf-11ea-8499-ee5f5608aad5.png)

## Proposal

To get deserialized errors closer to the native ones, when deserializing the error, we could use `Object.defineProperty` instead of a direct assignment to make the properties not enumerable. eg: here https://github.com/sindresorhus/serialize-error/blob/master/index.js#L54

```ts
for (const property of commonProperties) {
	if (typeof from[property] === 'string') {
        Object.defineProperty(to, property, {
          value: from[property]
        })
	}
}
```

I'm happy to make a PR if you agree with the proposal!

Thanks for your awesome work across the Node community ❤️

**Comment by sindresorhus** [comment]
Yes, definitely makes sense. The current behavior was just an oversight on my part. A PR would be great :)

**Comment by Jehoel** [comment]
@sindresorhus But this means that `JSON.stringify( serializeError( err ) )` won't include `message`, `stack`, and `code` - which defeats the point of using the `serialize-error` library in the first place :S
