### ISSUE TITLE
Nested Error's are not deserialized

### ISSUE THREAD

**Issue by jessetabak** [sindresorhus/serialize-error#46]
When I use nested Error's they are serialized, but not deserialized, am I missing something?:

```js
const {serializeError, deserializeError} = require('serialize-error');

class MyError extends Error {    
    constructor(message, innerError) {
        super(message);

        this.innerError = innerError;
    }
}

const error = new MyError('Error message', new Error('inner error'));
const serialized = serializeError(error)
console.log(serialized);
/* outputs:
{
    name: 'Error',
    message: 'Error message',
    stack: '<cut>',
    innerError: {
        name: 'Error',
        message: 'inner error',
        stack: '<cut>'
    }
}
*/
const deserialized = deserializeError(serialized);
console.log(deserialized);
/* outputs:
Error: Error message
    at <cut> {
  innerError: {}
}
*/
```

**Comment by sindresorhus** [comment]
There's no way for the `deserializeError` method to know that the `innerError` object is actually an `Error` type. The unserialized value it came from could have been a plain object.

There could indeed be an option to have such a behavior, but it's not a safe default.

**Comment by fregante** [comment]
I think this could be turned into a generic "deep serialize error" feature, so that I could serialize **and deserialized the output of `Promise.allSettled` for example.

Deep-serialize already seems to work: https://runkit.com/embed/eu5uful88qx9


```js
const {serializeError} = require("serialize-error")

const all = await Promise.allSettled([
    Promise.resolve('1'),
    Promise.reject(new Error('Sorry John'))
]);

serializeError(all);
```

But `deserializeError` would return a `NonError`
