### ISSUE TITLE
Add `isErrorObject` type guard / function

### ISSUE THREAD

**Issue by fregante** [sindresorhus/serialize-error#47]
What do you think about exporting a type-checker function (like `Array.isArray`) that doubles as a type guard?

```ts
export function isErrorObject(error: unknown): error is ErrorObject {
  return error && typeof error === 'object' && 'message' in error;
}
```

**Comment by sindresorhus** [comment]
What would you use it for that is related to this package?

**Comment by fregante** [comment]
To detect whether is a serialized error or regular error. Example:

``` ts
try {
…
} catch(error: unknown) {
  if (isErrorObject(error) && error.message === blah) {
    // ignore
  } else {
    throw error
  }
}
```

Typescript makes it a pain to check properties of unknown objects, even with `?.`, so a type guard would make it easier

**Comment by sindresorhus** [comment]
Yes, but why have it here and not in https://github.com/sindresorhus/is? And what properties should it enforce?

I think it should be named `isErrorLike`. This is consistent with TypeScript methods for duck-typing, like the `PromiseLike` type.

https://stackoverflow.com/questions/43712705/why-does-typescript-use-like-types

**Comment by fregante** [comment]
Here because `{message: string}` isn’t really an error on its own, but this package can turn it into one. I don’t think it would make sense in `is`

In this package the type ErrorObject could also make a little more tight because currently it matches `{}`, but that’s another issue. 

`isErrorLike` could also work but `isErrorObject` matches the name you’re using here.

**Comment by sindresorhus** [comment]
Ah, I see. Ok, sure, let's add.
