### ISSUE TITLE
Merge stack traces

### ISSUE THREAD

**Issue by fregante** [sindresorhus/serialize-error#49]
Tangentially related to this module, but is there any easy way to join the current stack trace (e.g. `Error.captureStackTrace`) with the the serialized error’s? Throwing a pre-existing error as-is may be confusing because its stack trace does not contain the current `throw` line’s stack.

Is the modern way to handle this via `.cause`?

```js
const current = new Error('Got an error')
current.cause = deserializeError(remoteError);
throw current;
```

Unfortunately I think it's not going to be well-supported for quite a while.

**Comment by sindresorhus** [comment]
No good way other than string handling: https://github.com/sindresorhus/got/blob/d4e34c7625c1c7000fd1b9af00e743669f83c83a/source/core/errors.ts#L55-L67

`Error#cause` is really the way to do this.

**Comment by fregante** [comment]
It may then be time to add another dependency to `got` 😃

`merge-error-stacks`?

**Comment by sindresorhus** [comment]
> merge-error-stacks? prepend-error-stack(-with-current-stack)?

Feel free to make that. I think it's better to just use a ponyfill for now: https://github.com/tc39/proposal-error-cause#implementations

**Comment by fregante** [comment]
Polyfills aren't the point, it's just a property. It's more about the tools, which don't show it (e.g. browser console)

**Comment by sindresorhus** [comment]
> which don't show it (e.g. browser console)

Hopefully, that will come sooner than later. People will start using "cause" and there will be demand.
