### ISSUE TITLE
Skip non-enumerable properties in destroyCircular

### ISSUE THREAD

**Issue by spudly** [sindresorhus/serialize-error#5]
I'm using AVA to test React components and running into a bizarre issue. In some circumstances, when I create a react component and the test fails, the error object has a reference to the react component somewhere deep inside `error.powerAssertContext`. I'm not sure how it gets the reference; must be getting it because of the espower babel transform somehow.

In React version 15.0.0-rc.2 they added warnings when you access `props.key` or `props.ref`. This is implemented with a getter property that is not enumerable and throws an error if accessed.

Now, because my error object references a React component, I end up with a very large meaningless stack trace when my tests fail.

In `destroyCircular` on [line 34](https://github.com/sindresorhus/serialize-error/blob/master/index.js#L34), you're using `Object.getOwnPropertyNames` and accessing each property it returns. The problem for me is that when you access the `key` or `ref` properties, React throws an error.

I can't think of any reason you would want to serialize non-enumerable properties, so I think the best solution here would be to use `Object.keys` instead of `Object.getOwnPropertyNames`. If that's not an option, could we at least wrap it in a try/catch and skip the properties that throw errors?

**Comment by jamestalmage** [comment]
I believe we used `getOwnPropertyNames` because `Error`s have some non-enumerable properties we did want (`name`?).

It believe back before `destroyCircular` was introduced those properties were explicitly copied. We could do that again: use `Object.keys` and copy a few specific non-enumerable ones.

**Comment by sindresorhus** [comment]
> We could do that again: use Object.keys and copy a few specific non-enumerable ones.

:+1:
