### ISSUE TITLE
Add support for (or document) Error#cause

### ISSUE THREAD

**Issue by fregante** [sindresorhus/serialize-error#50]
Context:

- https://github.com/tc39/proposal-error-cause
- https://v8.dev/features/error-cause
- https://nodejs.org/en/blog/release/v16.9.0/

I think this already kind of supported, but it should probably be documented and tested, especially if https://github.com/sindresorhus/serialize-error/issues/48 is implemented

**Comment by mayorandrew** [comment]
There is library [make-error-cause](https://www.npmjs.com/package/make-error-cause) which allows to create Errors with causes. It is fairly popular (600k downloads per week). The `cause` property is defined as `enumerable: false` there, so it is not automatically picked up by `serialize-error`.

I currently use custom `toJSON` method on the base error class to include `cause` property in the serialized object, like so:

```
import { BaseError as BaseMakeError } from 'make-error-cause';
import { serializeError } from 'serialize-error';
class BaseError extends BaseMakeError {
  public toJSON() {
    return {
      ...serializeError(this),
      cause: serializeError(this.cause)
    };
  }
}
```

Kudos for `isCalled` btw, it really helped here.

Still it would be nice if `cause` was included in the `commonProperties` list. Or even better, if `commonProperties` list was customizable via `options` on` serializeError`.

If that is something you're interested in, I can make a PR.

**Comment by fregante** [comment]
To add more context, here's the current support:

- serialization: fully works with the native `cause` property
- deserialization: `error.cause` is preserved but not deserialized

This is the result of:

```js
// Extra wrappers to test the stack visibility as well
function throwing () {
	throw new TypeError('original error')
}

function catcher() {
	try {
		throwing()
	} catch (typeError) {
		const extendedError = new Error('Wrapped error with more info')
		extendedError.cause = typeError;
		throw extendedError;
	}
}

async function init() {
	catcher()
}

init().catch(error => {
	console.log({
		error, 
		serialized: serializeError(error),
		seriaDeseria: deserializeError(serializeError(error))
	})
})
```

<img width="408" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/159170996-d81eaa50-e0dd-45d3-8a1f-754117fb1501.png">

**Comment by fregante** [comment]
Correction:

- the native Error#cause **does not** work

My example failed because I set the `cause` property directly in an env that does not support `Error#cause` natively. The difference is that the native `cause` is not enumerable.
