### ISSUE TITLE
Can type-fest be moved to devDependencies?

### ISSUE THREAD

**Issue by EricCrosson** [sindresorhus/serialize-error#51]
As far as I can tell, type-fest only provides TypeScript types (as opposed to values) which are entirely erased at runtime. Thus it would seem we only need type-fest available during compilation, which would be satisfied if it were a dev dependency. Am I missing something?

**Comment by sindresorhus** [comment]
> Am I missing something?

Yes. If `type-fest` is moved to dev dependencies, any TypeScript project importing this package will fail to compile as they need these types.

**Comment by EricCrosson** [comment]
But only if that TypeScript project installs dependencies with `npm install --prod`, right? I don't think compiling TypeScript in production environments is the normal use-case. Any TypeScript project installing its dependencies with `npm install` will also bring in devDependencies

**Comment by EricCrosson** [comment]
Here on [typescriptlang.org](https://www.typescriptlang.org/download), `typescript` is recommended to be installed as a devDependency. If it's true that only packages labeled `dependency` are available during compilation, how would any TypeScript project ever compile?

**Comment by sindresorhus** [comment]
Running `npm install` in your local project installs your direct `dependencies` and `devDependencies` **but not their `devDependencies`**.

Anyway, this is not really the place to ask general npm questions. => https://github.community/tag/npm
