### ISSUE TITLE
Use stricter type for JsonObject

### ISSUE THREAD

**Issue by gajus** [sindresorhus/serialize-error#52]
`JsonObject` that comes from 'type-fest' (annoyingly) includes undefined as valid value, which is not the case for json.

A better definition would be:

```ts
type JsonObject = { [key: string]: JsonValue, };
type JsonValue = JsonObject | JsonValue[] | boolean | number | string | null;
```

**Comment by sindresorhus** [comment]
> JsonObject that comes from 'type-fest' (annoyingly) includes undefined as valid value

It does not. It allows optional keys. You might want to use the [`exactOptionalPropertyTypes` flag](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#exact-optional-property-types).

**Comment by sindresorhus** [comment]
Context: https://github.com/sindresorhus/type-fest/pull/65
