### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES

### ISSUE THREAD

**Issue by vrecan** [sindresorhus/serialize-error#58]
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/runtime/app/node_modules/serialize-error/index.js from /var/runtime/app/src/webhooks/sendgrid.ts not supported.
Instead change the require of index.js in [redacted] to a dynamic import() which is available in all CommonJS modules.

```
import { serializeError } from 'serialize-error';
```

tsconfig:
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "outDir": "dist",
    "skipLibCheck": true,
    "strict": true,
    "target": "ES2020",
    "lib": ["esnext"]
  },
  "exclude": [
    "infrastructure/**/*.ts",
    "test/**/*.ts"
  ]
}
```

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by vrecan** [comment]
Thanks for the link, I read it but still don't understand where I am doing this wrong, I am using the correct import syntax but still getting this error.

**Comment by Xrazik1** [comment]
@sindresorhus Having same issue

**Comment by MattInternet** [comment]
Same issue here...

**Comment by luizfelipelaviola** [comment]
Same issue here... Project is already using ESM..

**Comment by luizfelipelaviola** [comment]
Works downgrading to 8.1.0

**Comment by aaonduollar** [comment]
Same issue here

**Comment by valtersantosmatosmanulife** [comment]
+1

**Comment by pedrolzoliveira** [comment]
+1

**Comment by Camuvingian** [comment]
+1
