### ISSUE TITLE
Version 9.1.1 with CRA default Babel config gives "Module parse failed"

### ISSUE THREAD

**Issue by gianpaolopascasidc** [sindresorhus/serialize-error#63]
Hi all,

after updating the library to the version 9.1.1 when i start debugging my React App (CRA) (npm start -> react-scripts start) gives the following error:

```
Failed to compile.

./node_modules/serialize-error/index.js 2:7
Module parse failed: Unexpected token (2:7)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export class NonError extends Error {
>   name = 'NonError';
| 
|   constructor(message) {

```

The updated `serialize-error` is a dependency of a private node-module. 
The babel config is the default one, the app is not ejected. No custom webpack config.

Reverting to 9.1.0 resolves the problem. 

PS

After checking the between releases differences, i think the problem has been generated from this commit: https://github.com/sindresorhus/serialize-error/commit/88a95be1e8ebb828586f464809838a2412d7fd04

**Comment by sindresorhus** [comment]
That syntax (class fields) is valid for the Node.js versions this package targets. This is not the place to ask for Webpack/Babel support.
