### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by kkorus** [sindresorhus/serialize-error#64]
I'm running my tests using Jest in with TypeScript, but it throws:

`
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/konrad/code/flip/flip-notification/app/node_modules/serialize-error/index.js:1
    export class NonError extends Error {
    ^^^^^^

    SyntaxError: Unexpected token 'export'
        at compileFunction (<anonymous>)

`

**Comment by sindresorhus** [comment]
This is a problem with Jest or your Jest config, not this project.

Try the Jest support channels.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
