### ISSUE TITLE
Optionally ignore `toJSON`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/serialize-error#66]
`serialize-error` automatically uses `toJSON`:

https://github.com/sindresorhus/serialize-error/blob/855fe3dc67e0376070007d72ac5cf88bafdb7d36/index.js#L61-L63

Unfortunately this introduces two unwanted behaviors:

- code can be executed by passing `{toJSON() { /*h4xor*/ }}`
- serialization is decided by the object owner, with which we might disagree (e.g. it might [exclude arbitrary properties](https://github.com/pixiebrix/pixiebrix-extension/blob/22c2a0b3bae84c42253eb8adb97f5bed15d68cd3/src/services/errors.ts#L90-L92))

### Possible solution

```js
serializeError(error, {toJSON: false})
```

**Comment by sindresorhus** [comment]
> code can be executed by passing {toJSON() { /*h4xor*/ }}

This is not a good argument. This applies to built-in APIs too. And also `.toString()`.

> serialization is decided by the object owner, with which we might disagree (e.g. it might [exclude arbitrary properties](https://github.com/pixiebrix/pixiebrix-extension/blob/22c2a0b3bae84c42253eb8adb97f5bed15d68cd3/src/services/errors.ts#L90-L92))

This is a valid argument.

**Comment by sindresorhus** [comment]
I'm ok with a `toJSON` option.
