### ISSUE TITLE
Wrong typescript definition for serializeError

### ISSUE THREAD

**Issue by ayanamidev** [sindresorhus/serialize-error#79]
If I am understanding the TypeScript correctly,

https://www.typescriptlang.org/docs/handbook/2/generics.html#working-with-generic-type-variables

https://github.com/sindresorhus/serialize-error/blob/main/index.js#L160

If the value input is function,

Should the type of return value must be also function as well?

If we still want to convert function value to string,

The type definition for input & return value should be `any` or `unknown` since they don't share the same type.

```
export function serializeError(error: any, options?: Options): any
```

**Comment by papb** [comment]
> Should the type of return value must be also function as well?

No...

> If we still want to convert function value to string,

According to [this test](https://github.com/sindresorhus/serialize-error/blob/2a77169cae632802b75c9962b8ae9a482c978ae2/test.js#L105-L112), yes we do.

> The type definition for input & return value should be `any` or `unknown` since they don't share the same type.

There's nothing wrong with input type and return type not sharing the same type.

**Comment by papb** [comment]
Also, in the future, prefer using a _permalink_ when linking to code. So instead of

> https://github.com/sindresorhus/serialize-error/blob/main/index.js#L160

You should use:

https://github.com/sindresorhus/serialize-error/blob/2a77169cae632802b75c9962b8ae9a482c978ae2/index.js#L160

![image](https://user-images.githubusercontent.com/20914054/172085252-6929f620-c076-4c18-a350-a17b2cec1af3.png)

**Comment by ayanamidev** [comment]
> There's nothing wrong with input type and return type not sharing the same type.

@papb What I wanted to say is that the current type definition is wrong

https://github.com/sindresorhus/serialize-error/blob/main/index.d.ts#L108

Type definition is enforcing that the return value should have the same type of the input, while we convert function inputs to string

**Comment by fregante** [comment]
Indeed the type is incorrect. `serializeError` never returns the same type; only `deserializeError` may return the same exact object if it's `instanceof Error`

**Comment by fregante** [comment]
> Type definition is enforcing that the return value should have the same type of the input

That is correct. `serializeError` returns the same value if it's not an `object` and not a `function`

https://github.com/sindresorhus/serialize-error/blob/2a77169cae632802b75c9962b8ae9a482c978ae2/index.js#L141-L166
