### ISSUE TITLE
Keep old versions of the lib on a separate branch

### ISSUE THREAD

**Issue by belchior** [sindresorhus/serialize-error#85]
Some big and legacy systems can't upgrade to new versions of nodejs. The life of developers that maintain this systems will be more easy if the code of old versions of this lib are preserved in a branch. Optionally adding the nodejs version constraints at package.json#engines.node

**Comment by sindresorhus** [comment]
I follow the Node.js versions the Node.js team supports. I cannot commit to support older unsupported Node.js versions.
