### ISSUE TITLE
v9+ throws ERR_REQUIRE_ESM when imported

### ISSUE THREAD

**Issue by jmechevarria** [sindresorhus/serialize-error#95]
I just installed the latest version of this library, and when first tried to use it (`import { serializeError } from 'serialize-error'`), I got this error right away.

```
const serialize_error_1 = require("serialize-error");

Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/serialize-error/index.js from .../bdist/backend/middlewares/ErrorHandler.js not supported.
Instead change the require of index.js in .../bdist/backend/middlewares/ErrorHandler.js to a dynamic import() which is available in all CommonJS modules.
     at Object.<anonymous> (.../bdist/backend/middlewares/ErrorHandler.js:6:27) {
   code: 'ERR_REQUIRE_ESM'
 }
 ```

I started downgrading versions until I got it to work at v8.1

I'm using many other packages in this project, first time I get this specific error.

Using Node.js v20.11.0 and TS 5.3.3

Is there something wrong with how I'm importing/using this library?

Thanks

**Comment by sindresorhus** [comment]
The error says it all. The package requires ESM.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
